[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-frozen-lockfile"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling
[[redirects]]
  from = "/"
  to = "/thank-you/"
  status = 302
  conditions = {Role = ["admin"]}

# Handle form submissions
[forms]
  [forms.contact]
    name = "Contact Form"
    honeypot = "bot-field"

# Performance optimization headers
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

# HTML caching - shorter duration for content updates
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding" 